
---
title: "Trabajo Final"
date: "8 de noviembre de 2017"
output: html_document
---
<h3>Autores</h3>
<ul>
  <li>Mateo Zuluaga <br> ID. 1045026217</li>
  <li>Brahian Gómez <br> ID. 1041234487</li>
  <li>Andrés Acosta <br> ID. 1026154354</li>
  <li>Jose Toquica <br> ID. 1020450656</li>
</ul>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}

library(xlsx)
library(dplyr)


datos <- read.xlsx("datos.xlsx",1)


for (i in 1:2){
  
  dbb <- paste(paste(datos[i,"nombre_base_datos"]),".csv", sep = "")
  db <- read.csv(dbb)


distancia <- datos[i,'distancia']
db <- db %>%
        mutate(fecha= as.POSIXct(timestamp/1000, origin = "1970-01-01"))
db_1 <- db %>%
  mutate(tiempo = timestamp %/% 100) %>%
  group_by(tiempo) %>%
  summarise(AccX = mean(AccX, na.rm = TRUE),
            AccY = mean(AccY, na.rm = TRUE),
            AccZ = mean(AccZ, na.rm = TRUE))
db_1 <- db_1 %>%
            mutate(accT = sqrt(AccX ^ 2 + AccY ^ 2 + AccZ ^ 2))

db_1 <- db_1 %>% filter(!is.na(accT))
spec2 <- spec.pgram(db_1$accT, las = 1)

maxFrec <- spec2$freq[which(spec2$spec == max(spec2$spec))]


tiempoTotal_db <- db$fecha[nrow(db)] - db$fecha[1]
as.vector(tiempoTotal_db) * 600

as.vector(tiempoTotal_db) * 600 * maxFrec

longPaso2 <- distancia/(as.vector(tiempoTotal_db) * 600 * maxFrec)
longPaso2
datos[i,"long_paso_c"] <- longPaso2
}
```

```{r}

library(xlsx)
library(dplyr)

datos <- read.xlsx("datos.xlsx",1)


for (i in 1:2){
  
  dbb <- paste(paste(datos[i,"nombre_base_datos"]),".csv", sep = "")
  db <- read.csv(dbb)


distancia <- datos[i,'distancia']
db <- db %>%
        mutate(fecha= as.POSIXct(timestamp/1000, origin = "1970-01-01"))
db_1 <- db %>%
  mutate(tiempo = timestamp %/% 100) %>%
  group_by(tiempo) %>%
  summarise(AccX = mean(AccX, na.rm = TRUE),
            AccY = mean(AccY, na.rm = TRUE),
            AccZ = mean(AccZ, na.rm = TRUE))
db_1 <- db_1 %>%
            mutate(accT = sqrt(AccX ^ 2 + AccY ^ 2 + AccZ ^ 2))

db_1 <- db_1 %>% filter(!is.na(accT))
spec2 <- spec.pgram(db_1$accT, las = 1)

maxFrec <- spec2$freq[which(spec2$spec == max(spec2$spec))]


tiempoTotal_db <- db$fecha[nrow(db)] - db$fecha[1]
as.vector(tiempoTotal_db) * 600

as.vector(tiempoTotal_db) * 600 * maxFrec

longPaso2 <- distancia/(as.vector(tiempoTotal_db) * 600 * maxFrec)
longPaso2
datos[i,"long_paso_c"] <- longPaso2
}

```